# Generated by Django 3.2.17 on 2023-02-08 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_bebidavariacion_id_alter_direccion_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='direccion',
            old_name='cuidad',
            new_name='ciudad',
        ),
        migrations.RenameField(
            model_name='direccion',
            old_name='addres_type',
            new_name='tipo_de_direccion',
        ),
        migrations.RenameField(
            model_name='orden',
            old_name='envio_direccion',
            new_name='direccion_de_envio',
        ),
        migrations.RenameField(
            model_name='orden',
            old_name='facturacion_direccion',
            new_name='direccion_de_facturacion',
        ),
    ]
